language: ruby
rvm: 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: eQr4uoBXKyPNRqZ4cRZHvdBsRpjLvdtz6QY2zAwg2j7+Q9yD+208ymxhhf9hNJYMqsbphs4pCsdG5SN6V83riJT7eoTNSt75inLQGYpdlppp2Ki77vIHUoBwz4vJ6okwENYtEGw59/avLa6DtPylpkOqb/Eit4kIv2Db1cnM73OX8Bk/O23MmZBrvjdps9Dy3+5v3pq6DKGjoSdjv8OWkH+cf0A664gFYBbcSxmtNsU0CHvlja46J7Czj2WGYHA/Y9X+YHv2zVe0G9DRglOz9tHMaUlfV17Jn6OHyz5jJRA0Cgq2yQiGfsdyj7JGnE2tak0DOLpK/Cc0JqiwQqDgtihzc7CD/aLaXZ9NWwq5z73Oph+mYUwH3rGthU9AbnG1Nmli2awuTi0r6eUfoxavoAR1iWa8WDWqlSOM33llmjartIzjK9hoVTbISsA0dCGfEeSMhQmc7i1M+qrMw6QtzwVb03G2ssvBPcka5qbedU8b8ZUwP4D8SAcR0UcPRJ4ugBGUeIc4RWkGgnbdRlBmziWftnXO2MQxJvthIiPN3RsSSkhNoC9pXxhdXyMyskGMq+9GpXpmjnXUR0qtpuLNRj5vwl8nRJDKn9aVgpYqPAD4S0i7V9bDevyNz5TUWXpsmnKd6iXJenCVHKkrHryfVHOnshpapFFkzlsh6pHSE1I=
