# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Ushering In Growth'
description: "My development story begins here."

# Author's info
author: 'Jordan Taylor'
# edit 'categories' in the front matter of every post to match this username
nickname: jt
bio: 'Software Engineer. DC. Radford Baseball Alum.'
location: 'Viringia, USA'
url: 'https://github.com/jtaylor32'
image: 'assets/images/gopher-me.png'

short_url: 'github'
google_analytics: UA-81287416-1
disqus:
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: waluigi27
repo: blog
branch: master
relative_source: ./
destination: ./blog-pages/
production_url:  http://cloudhermit.com
source_url:      https://github.com/waluigi27/blog/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml